import { getApiString } from '$lib/state.svelte.ts';

import createClient from "openapi-fetch";
import type { paths } from "./openapi.json"; // generated by openapi-typescript

const apiClient = createClient<typeof paths>({ baseUrl: getApiString() });

export default apiClient;
